"""risk rules table and chat citation/feedback normalization

Revision ID: 2c8796c984d6
Revises: 61dca5b1b8df
Create Date: 2026-09-25 19:53:53.566990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c8796c984d6'
down_revision: Union[str, Sequence[str], None] = '61dca5b1b8df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('field_code', sa.String(), nullable=True),
    sa.Column('base_score', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code')
    )
    op.create_table('citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('ref', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('regulation_id', sa.UUID(), nullable=True),
    sa.Column('regulation_title', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('quoted_span', sa.Text(), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.drop_column('chat_messages', 'feedback')
    op.drop_column('chat_messages', 'citations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('chat_messages', sa.Column('feedback', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('message_feedback')
    op.drop_table('citations')
    op.drop_table('risk_rules')
    # ### end Alembic commands ###
