"""add pgvector embedding column to regulation_chunks

Revision ID: b898f28a4405
Revises: 2c8796c984d6
Create Date: 2026-09-26 15:19:55.024315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b898f28a4405'
down_revision: Union[str, Sequence[str], None] = '2c8796c984d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('regulation_chunks', sa.Column('embedding', pgvector.sqlalchemy.Vector(384), nullable=True))
    op.create_index('ix_regulation_chunks_embedding_hnsw', 'regulation_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_regulation_chunks_embedding_hnsw', table_name='regulation_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_column('regulation_chunks', 'embedding')
    # ### end Alembic commands ###
